import { useState } from 'react';
import Head from 'next/head';
import JSON5 from 'json5';
import { map } from 'lodash-es';

function getType(obj: any) {
    var type = Object.prototype.toString.call(obj);
    return type.split(' ')[1].replace(']', '').toLowerCase();
}

function jsonFrom(input: string) {
    const string = input.trim();
    if (!string) {
        return;
    }
    let result = null;
    try {
        result = JSON5.parse(string);
    } catch (err) {
        console.error(err);
    }
    return result;
}

function arrayFrom(json: any) {
    const queue = [];
    let next = json;
    while (next !== undefined) {
        if (getType(next) == 'array') {
            if (next.length > 0) {
                var type = getType(next[0]);
                var scalar =
                    type == 'number' || type == 'string' || type == 'boolean' || type == 'null';
                if (!scalar) return next;
            }
        }
        if (getType(next) == 'object') {
            for (var key in next) {
                queue.push(next[key]);
            }
        }
        next = queue.shift();
    }
    return json;
}

function parseObject(obj: any, path = '') {
    const type = getType(obj);
    const scalar = type == 'number' || type == 'string' || type == 'boolean' || type == 'null';
    if (type == 'array' || type == 'object') {
        let d: any = {};
        for (let i in obj) {
            const newD = parseObject(obj[i], path + i + '/');
            d = Object.assign(d, newD);
        }
        return d;
    } else if (scalar) {
        let d: any = {};
        const endPath = path.substring(0, path.length - 1);
        d[endPath] = obj;
        return d;
    }
    return {};
}

function formatSource(input: string) {
    const json = jsonFrom(input);
    const obj = arrayFrom(json);
    return parseObject(obj);
}

export default function Home() {
    const [source, setSource] = useState('');
    const [output, setOutput] = useState({});

    const handleChange = (e: any) => {
        const input = e.target.value;
        setSource(input);
        const result = formatSource(input);
        setOutput(result);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div className='flex'>
                <div className='h-screen w-1/2 border'>
                    <textarea
                        className='w-full h-full p-4 resize-none outline-none'
                        placeholder='请输入JSON'
                        value={source}
                        onChange={handleChange}
                    />
                </div>

                <div className='h-screen w-1/2 border overflow-y-auto'>
                    <table className='h-full'>
                        <tbody>
                            {map(output, (v, k) => {
                                return (
                                    <tr key={k}>
                                        <td className='border border-slate-300'>{k}</td>
                                        <td className='border border-slate-300'>{v}</td>
                                    </tr>
                                );
                            })}
                        </tbody>
                    </table>
                </div>
            </div>
        </>
    );
}
